right_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_joint
    joint_speed: 10.0
    motor:
        id: 1
        init: 2048
        min: 0
        max: 4095

left_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_joint
    joint_speed: 10.0
    motor:
        id: 2
        init: 2048
        min: 0
        max: 4095
